# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jhgao/mpsica/2/mPSI-CA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jhgao/mpsica/2/mPSI-CA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jhgao/mpsica/2/mPSI-CA/CMakeFiles /home/jhgao/mpsica/2/mPSI-CA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jhgao/mpsica/2/mPSI-CA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sha_asm

# Build rule for target.
sha_asm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sha_asm
.PHONY : sha_asm

# fast build rule for target.
sha_asm/fast:
	$(MAKE) -f cryptoTools/CMakeFiles/sha_asm.dir/build.make cryptoTools/CMakeFiles/sha_asm.dir/build
.PHONY : sha_asm/fast

#=============================================================================
# Target rules for targets named cryptoTools

# Build rule for target.
cryptoTools: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptoTools
.PHONY : cryptoTools

# fast build rule for target.
cryptoTools/fast:
	$(MAKE) -f cryptoTools/CMakeFiles/cryptoTools.dir/build.make cryptoTools/CMakeFiles/cryptoTools.dir/build
.PHONY : cryptoTools/fast

#=============================================================================
# Target rules for targets named libOTe

# Build rule for target.
libOTe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libOTe
.PHONY : libOTe

# fast build rule for target.
libOTe/fast:
	$(MAKE) -f libOTe/CMakeFiles/libOTe.dir/build.make libOTe/CMakeFiles/libOTe.dir/build
.PHONY : libOTe/fast

#=============================================================================
# Target rules for targets named libOPRF

# Build rule for target.
libOPRF: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libOPRF
.PHONY : libOPRF

# fast build rule for target.
libOPRF/fast:
	$(MAKE) -f libOPRF/CMakeFiles/libOPRF.dir/build.make libOPRF/CMakeFiles/libOPRF.dir/build
.PHONY : libOPRF/fast

#=============================================================================
# Target rules for targets named frontend.exe

# Build rule for target.
frontend.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 frontend.exe
.PHONY : frontend.exe

# fast build rule for target.
frontend.exe/fast:
	$(MAKE) -f frontend/CMakeFiles/frontend.exe.dir/build.make frontend/CMakeFiles/frontend.exe.dir/build
.PHONY : frontend.exe/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... sha_asm"
	@echo "... cryptoTools"
	@echo "... libOTe"
	@echo "... libOPRF"
	@echo "... frontend.exe"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

